require("varant.plugins-setup")
require("varant.core.options")
require("varant.core.keymaps")
require("varant.core.colorscheme")
require("varant.plugins.comment")
require("varant.plugins.nvim-tree")
require("varant.plugins.lualine")
require("varant.plugins.telescope")
require("varant.plugins.nvim-cmp")
require("varant.plugins.lsp.mason")
require("varant.plugins.lsp.lspsaga")
require("varant.plugins.lsp.lspconfig")
require("varant.plugins.lsp.null-ls")
require("varant.plugins.autopairs")
require("varant.plugins.treesitter")
require("varant.plugins.gitsigns")
require("varant.plugins.barbar")
-- require("varant.plugins.bufferline")
